name: status-check-1.yml
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for label winforms-xtraproducts-tests
        id: check_label
        uses: actions/github-script@v7
        with:
          script: |
            const label = 'winforms-xtraproducts-tests';
            const labels = context.payload.pull_request?.labels.map(l => l.name) || [];
            return labels.includes(label);

      # Can go without this part but use native thing from github, however not sure at this moment how it is
      # Explanation can be found at this exact action actually
      - name: Cancel workflow if label not present
        if: steps.check_label.outputs.result != 'true'
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          workflow_id: ${{ github.workflow }}
  
  build:
    uses: ./.github/workflows/build-binaries.yml
    secrets: inherit
  
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from release
        if: steps.check_release.outputs.exists == 'true'
        run: |
          echo "Downloading artifact from release..."
          curl -L -o diff.zip https://github.com/${{ github.repository }}/releases/download/${{ steps.set_tag.outputs.tag }}/diff.zip
          curl -L -o modifications.xml https://github.com/${{ github.repository }}/releases/download/${{ steps.set_tag.outputs.tag }}/modifications.xml

      - name: List files
        run: |
          echo "Listing downloaded files..."
          ls -la